const messageTitles = {
    NEW_MESSAGE: 'NEW_MESSAGE',
    AUTHENTICATE_RESPONSE: 'AUTHENTICATE_RESPONSE',
    AUTHENTICATE_REQUEST: 'AUTHENTICATE_REQUEST',
    NEED_AUTHENTICATE: 'NEED_AUTHENTICATE'
}

module.exports = {
    messageTitles
}